**

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!tsconfig.json

!patches/
!patches/**

!packages/
!packages/client-sdk/
!packages/client-sdk/**
!packages/react-sdk/
!packages/react-sdk/**

!ui/
!ui/**
ui/node_modules
ui/dist
ui/dev-dist
ui/release
ui/binaries
ui/.polpo
ui/.vite

!website/
!website/package.json

**/node_modules
**/.turbo
**/.vite
**/coverage
**/*.log
